export const types = {
  login: "[auth] Login",
  logout: "[auth] Logout",
  uiSetError: "[UI] Set Error",
  uiResetError: "[UI] Remove Error",
  uiStartLoading: "[UI] Start loading",
  uiFinishLoading: "[UI] Finish loading",
  notesAddNew: "[Notes] New note",
  notesActive: "[Notes] Set active note",
  notesLoad: "[Notes] Load notes",
  notesUpdate: "[Notes] Update note",
  notesFileUrl: "[Notes] Updated image ulr",
  notesDelete: "[Notes] Delete note",
  notesLogoutCleaning: "[Note] Logout Cleaning",
};
